[IMP]Wireshark dependency update to 4.0; add out-of-bounds control to specify frame dissect result func;

diff --git a/include/wireshark/packaging/macosx/osx-dmg.sh.in b/include/wireshark/packaging/macosx/osx-dmg.sh.in
--- a/include/wireshark/packaging/macosx/osx-dmg.sh.in
+++ b/include/wireshark/packaging/macosx/osx-dmg.sh.in
@@ -5,9 +5,12 @@
 set -e
 
 # Defaults
+app_name="Wireshark"
 dmgbuild="@DMGBUILD_EXECUTABLE@"
-version="@VERSION@"
-settings_file="@CMAKE_BINARY_DIR@/packaging/macosx/dmgbuild-settings.py"
+version="@PROJECT_VERSION@"
+log_version="@LOG_PROJECT_VERSION@"
+app_settings_file="@CMAKE_BINARY_DIR@/packaging/macosx/wireshark-app.dmgbuild"
+dsym_settings_file="@CMAKE_BINARY_DIR@/packaging/macosx/wireshark-dsym.dmgbuild"
 architecture=""
 
 # Help message
@@ -24,8 +27,8 @@ OPTIONS
 	-h,--help
 		Display this help message.
 
-Icons are positioned and the background image is set in
-dmgbuild-settings.py.in.
+Icons are positioned and the background image is set in wireshark-app.dmgbuild.in
+and wireshark-dsym.dmgbuild.in.
 "
 }
 
@@ -34,20 +37,14 @@ if [ ! -x "$dmgbuild" ] ; then
 	exit 1
 fi
 
-if lipo Wireshark.app/Contents/MacOS/Wireshark -verify_arch arm64 ; then
-	architecture="Arm 64"
-elif lipo Wireshark.app/Contents/MacOS/Wireshark -verify_arch x86_64 ; then
-	architecture="Intel 64"
-else
-	echo "Error: Wireshark.app missing or has unknown architecture."
-	lipo Wireshark.app/Contents/MacOS/Wireshark -detailed_info
-	exit 1
-fi
-
 # Parse command line arguments
 while [ "$1" != "" ]
 do
 	case $1 in
+		-a|--app-name)
+			shift 1
+			app_name="$1"
+			;;
 		-h|--help)
 			help
 			exit 0 ;;
@@ -58,27 +55,54 @@ do
 	shift 1
 done
 
-vol_name="Wireshark ${version}"
-img_name="$vol_name $architecture.dmg"
+if lipo "$app_name.app/Contents/MacOS/$app_name" -verify_arch arm64 ; then
+	architecture="Arm 64"
+elif lipo "$app_name.app/Contents/MacOS/$app_name" -verify_arch x86_64 ; then
+	architecture="Intel 64"
+else
+	echo "Error: $app_name.app missing or has unknown architecture."
+	lipo "$app_name.app/Contents/MacOS/$app_name" -detailed_info
+	exit 1
+fi
 
-echo -e "\\nCREATE WIRESHARK DISK IMAGE\\n"
+if [[ $app_name = Log* ]] ; then
+	version=$log_version
+	app_settings_file="@CMAKE_BINARY_DIR@/packaging/macosx/logray-app.dmgbuild"
+	dsym_settings_file="@CMAKE_BINARY_DIR@/packaging/macosx/logray-dsym.dmgbuild"
+fi
+
+app_vol_name="$app_name ${version}"
+app_img_name="$app_vol_name $architecture.dmg"
+
+printf "\nCreating application disk image %s\n" "$app_img_name"
 
 "$dmgbuild" \
 	--no-hidpi \
-	-s "$settings_file" \
-	"$vol_name" \
-	"$img_name" || exit 1
+	-s "$app_settings_file" \
+	"$app_vol_name" \
+	"$app_img_name" || exit 1
 
-echo -e "\\nSIGN WIRESHARK DISK IMAGE\\n"
+dsym_vol_name="$app_name dSYM ${version}"
+dsym_img_name="$dsym_vol_name $architecture.dmg"
+
+printf "\nCreating debugging symbols disk image %s\n" "$dsym_img_name"
+
+"$dmgbuild" \
+	--no-hidpi \
+	-s "$dsym_settings_file" \
+	"$dsym_vol_name" \
+	"$dsym_img_name" || exit 1
+
+printf "\nSigning disk images\n"
 
 # TN2206, "Signing Disk Images"
 if [ -n "$CODE_SIGN_IDENTITY" ] ; then
-	echo -e "Signing $img_name"
+	echo -e "Signing $app_img_name and $dsym_img_name"
 	codesign \
 		--sign "Developer ID Application: $CODE_SIGN_IDENTITY" \
 		--timestamp \
 		--verbose \
-		"$img_name"
+		"$app_img_name" "$dsym_img_name"
 fi
 
 exit 0
diff --git a/include/wireshark/packaging/source/git-export-release.sh.in b/include/wireshark/packaging/source/git-export-release.sh.in
--- a/include/wireshark/packaging/source/git-export-release.sh.in
+++ b/include/wireshark/packaging/source/git-export-release.sh.in
@@ -33,36 +33,65 @@ shift $(( OPTIND - 1 ))
 
 # The remaining parameter, if set, is a package version such as 3.4.5
 # or 3.4.5-67-gabcd4321
-# By default the version from make-version.pl + CMake is used.
-VERSION=@VERSION@
+# By default the version from make-version.py + CMake is used.
+PROJECT_VERSION=@PROJECT_VERSION@
 if test -n "${1-}"; then
-    VERSION="$1"
+    PROJECT_VERSION="$1"
 fi
 
-if [ -f "${DESTDIR}/wireshark-$VERSION.tar.xz" ] ; then
-    echo "${DESTDIR}/wireshark-$VERSION.tar.xz exists."
-    exit 0
+TARBALL="${DESTDIR}/wireshark-${PROJECT_VERSION}.tar.xz"
+
+# A tarball produced by 'git archive' will have the $Format string
+# substituted due to the use of 'export-subst' in .gitattributes.
+# shellcheck disable=SC2016
+COMMIT='0cbe09cd796b2ea24c6069b76ea16df7f51cf67b'
+
+if [[ $COMMIT != \$F* ]] ; then
+    # This file was extracted from a tarball produced by git archive
+    # and so we are not in a git repository.
+    if [[ -f "$TARBALL" ]] ; then
+        # git get-tar-commit-id works outside a git repo, as it
+        # only reads the first 1024 bytes of the tar extended header.
+        if [[ $(git get-tar-commit-id < <(xzcat "$TARBALL")) == "$COMMIT" ]] ; then
+            echo "$TARBALL commit ID matches $COMMIT."
+        else
+            # Allow people to make changes to a downloaded source tarball
+            # and re-tar it?
+            echo "WARNING: $TARBALL is not the original git archive."
+        fi
+        exit 0
+    fi
+
+    echo ""
+    echo "The build system cannot produce a source tarball outside of a git repository."
+    echo "If you are trying to build an RPM package from source extracted from a tarball,"
+    echo "copy it (i.e., wireshark-${PROJECT_VERSION}.tar.xz) to"
+    echo "$DESTDIR"
+    echo "and run the build command again."
+
+    exit 1
 fi
 
-COMMIT="HEAD"
-if [ -n "${CI_COMMIT_SHA-}" ] ; then
-    COMMIT=$CI_COMMIT_SHA
+COMMIT="${CI_COMMIT_SHA:-HEAD}"
+
+STASH_ID=$(git stash create || echo "")
+if [[ -n "$STASH_ID" ]] ; then
+    COMMIT="$STASH_ID"
 fi
 
-STASH_POP=false
-if ! git diff-index "$COMMIT" ; then
-    git stash --keep-index
-    COMMIT="stash@{0}"
-    STASH_POP=true
+if [ -f "$TARBALL" ] ; then
+    printf "Found %s\\n" "$TARBALL"
+    if TARBALL_ID=$(git get-tar-commit-id < <(xzcat "$TARBALL")) && COMMIT_ID=$(git rev-parse --verify "$COMMIT") ; then
+        if [[ $TARBALL_ID == "$COMMIT_ID" ]] ; then
+            echo "$TARBALL commit ID matches $COMMIT."
+            exit 0
+        fi
+    fi
 fi
 
-echo "Creating ${DESTDIR}/wireshark-$VERSION.tar.xz from $COMMIT"
+echo "Creating $TARBALL from $COMMIT"
 
 XZ_OPTS=
 echo . | xz --threads=0 > /dev/null 2>&1 && XZ_OPTS=--threads=0
 
-git archive --prefix="wireshark-${VERSION}/" "$COMMIT" | xz $XZ_OPTS > "${DESTDIR}/wireshark-${VERSION}.tar.xz"
-
-if $STASH_POP ; then
-    git stash pop
-fi
+git archive --prefix="wireshark-${PROJECT_VERSION}/" "$COMMIT" | xz $XZ_OPTS > "$TARBALL"
